# Generated by Django 5.2.17 on 2026-08-21 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, unique=True)),
                ('MinLongitudeDegrees', models.FloatField()),
                ('MinLatitudeDegrees', models.FloatField()),
                ('MaxLongitudeDegrees', models.FloatField()),
                ('MaxLatitudeDegrees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userIp', models.CharField(default=None, max_length=150, primary_key=True, serialize=False)),
                ('firstCnxDateTime', models.DateTimeField(auto_now_add=True)),
                ('lastCnxDateTime', models.DateTimeField(auto_now_add=True)),
                ('connexions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AirlineAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraftICAOcode', models.CharField(max_length=50)),
                ('aircraftFullName', models.CharField(max_length=500)),
                ('numberOfAircraftsInService', models.IntegerField(default=0)),
                ('maximumOfPassengers', models.IntegerField(default=0)),
                ('costsFlyingPerHoursDollars', models.FloatField(default=0)),
                ('crewCostsPerFlyingHoursDollars', models.FloatField(default=0)),
                ('turnAroundTimesMinutes', models.FloatField(default=0)),
                ('landingLengthMeters', models.FloatField(default=0)),
                ('takeOffMTOWLengthMeters', models.FloatField(default=0)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.airline')),
            ],
            options={
                'unique_together': {('airline', 'aircraftICAOcode')},
            },
        ),
        migrations.CreateModel(
            name='AirlineRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartureAirport', models.CharField(max_length=500)),
                ('DepartureAirportICAOCode', models.CharField(max_length=50)),
                ('ArrivalAirport', models.CharField(max_length=500)),
                ('ArrivalAirportICAOCode', models.CharField(max_length=50)),
                ('airline', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airlines.airline')),
            ],
            options={
                'unique_together': {('DepartureAirportICAOCode', 'ArrivalAirportICAOCode')},
            },
        ),
        migrations.CreateModel(
            name='AirlineCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAborted', models.BooleanField()),
                ('flightDurationSeconds', models.FloatField()),
                ('initialTakeOffMassKg', models.FloatField()),
                ('targetCruiseLevelFeet', models.FloatField(default=0.0)),
                ('adepRunway', models.CharField(default=None, max_length=50)),
                ('adesRunway', models.CharField(default=None, max_length=50)),
                ('finalMassKg', models.FloatField()),
                ('finalLengthMeters', models.FloatField(default=0.0)),
                ('reducedClimbPowerCoeff', models.FloatField(default=0.0)),
                ('airline', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airlines.airline')),
                ('airlineAircraft', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airlines.airlineaircraft')),
                ('airlineRoute', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airlines.airlineroute')),
            ],
        ),
        migrations.CreateModel(
            name='AirlineRouteWayPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('WayPoint', models.CharField(max_length=100)),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.airlineroute')),
            ],
        ),
    ]
